create table outbox
(
    id             bigint generated by default as identity primary key,
    aggregate_type varchar(255) not null,
    aggregate_id   varchar(255) not null,
    payload        jsonb,
    created_at     timestamp  not null,
    published_at   timestamp
);