create table outbox
(
    id             bigint generated by default as identity primary key,
    aggregate_type varchar(255) not null,
    aggregate_id   varchar(255) not null,
    payload        jsonb,
    created_at     timestamp  not null,
    published_at   timestamp
);


-- Add test data
insert into outbox (aggregate_type, aggregate_id, payload, created_at, published_at)
select 'test_type',
       'test_id_' || i,
       '{}'::jsonb,
       now(),
       null
from generate_series(1, 10000) as i;