create table outbox
(
    id             bigint generated by default as identity primary key,
    aggregate_type varchar(255) not null,
    aggregate_id   varchar(255) not null,
    payload        jsonb,
    created_at     timestamptz  not null default now(),
    published_at   timestamptz
);

create index outbox_unpublished_id_idx
    on outbox (id)
    where published_at is null;


-- TEST DATA

-- Published records
insert into outbox (aggregate_type, aggregate_id, payload, created_at, published_at)
select 'test_type',
       'test_id_' || i,
       '{}'::jsonb,
       now(),
       now()
from generate_series(1, 10000) as i;

-- Unpublished records
insert into outbox (aggregate_type, aggregate_id, payload, created_at, published_at)
select 'test_type',
       'test_id_' || i,
       '{}'::jsonb,
       now(),
       null
from generate_series(1, 1000) as i;

-- Important to refresh stats so that the PG planner sees it immediately
analyze outbox;